
name = "DashDaq"
uuid = "1b08a953-4be3-4667-9a23-240089a44fa3"
authors = ["The Plotly Team <dashdaq@plotly.com>"]
version = "0.5.0"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compact]
julia = "1.1"
Dash = ">=0.1"
